### ISSUE TITLE
`rand` should be defined for `AbstractRNG`

### ISSUE THREAD

**Issue by JeffBezanson** [Element-126/LorentzVectors.jl#5]
This package defines a method `rand(::MersenneTwister, ...)`, but as far as I can tell the method is fully generic with respect to RNG, so should be defined for AbstractRNG instead. Will be needed in julia 1.7 as the default RNG has changed.

**Comment by JLTastet** [comment]
Good catch! I've just pushed a fix, and I'll create a release as soon as the tests have passed on all platforms. Thanks for reporting
